<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_RESTapi" Id="{bd5d33f5-92dc-4ee4-8d05-f7266e31974c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RESTapi
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbREST : 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_RESTapi">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>